config/routes.rb
Rails.application.routes.draw do
  
  get 'staticpages/about'

  root 'articles#show'
  post 'wiki_scrape' => 'articles#wiki_scrape'

  get '/topic', to: 'topics#show'
  get '/user', to: 'users#show'  

  post '/relevant', to: 'scores#train_relevant'
  post '/irrelevant', to: 'scores#train_irrelevant'

 

end

app/models/score.rb
require 'pry'

class Score < ActiveRecord::Base  

  def self.classify(topic, text)
    (self.classifications(topic, text).sort_by { |a| -a[1] })[0][0]
  end

  def self.classifications(topic, text)
    score = Hash.new
    training_count = Score.where(topic: topic).sum("count")
    ['relevant', 'irrelevant'].each do |category|
      score[category] = 0
      total = Score.where(topic: topic, category: category).sum("count")
      text.word_hash.each do |word, count|
        w = Score.where(topic: topic, category: category, word: word)
        w.size > 0 ? s = w.first.count : s = 0.1
        score[category] += Math.log(s/total.to_f)
      end
      c = Score.where(topic: topic, category: category)
      c.size > 0 ? s = c.sum("count") : s = 0.1
      score[category] += Math.log(s/training_count)
    end
    return score

  end

  def self.train (topic, category, text)
    text.word_hash.each do |word, count|
      score = Score.find_or_create_by(topic: topic, word: word, category: category)
      score.count += count
      score.save
    end
  end

  def self.show?(topic, text)
    training_count = Score.where(topic: topic).sum("count")
    return (classify(topic, text) == "relevant" || training_count < 50)
  end
end

app/models/scraper.rb
class Scraper
	
	def initialize(topic)
		url = "http://en.wikipedia.org/wiki/#{topic}"
		@doc = Nokogiri::HTML(open(url))
	end


	def parse
		results = Hash.new
		@doc.css('div.toc ul li').each do |li|
			number = li.css(".tocnumber").first.text.to_f
			text = li.css(".toctext").first.text	
			results[number]=text
		end
		results
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	def show
	end

	def wiki_scrape
		topic = params["topic"].gsub(" ","_").downcase
		scraper = Scraper.new(topic)
		wiki_results = scraper.parse_to_json
		# render :json => {data: wiki_results}
		# render :json => wiki_results
	end

end

app/controllers/scores_controller.rb
require 'pry'
class ScoresController < ApplicationController

  def train_relevant
    Score.train(params[:topic], 'relevant', params[:train])
  end

  def train_irrelevant
    Score.train(params[:topic], 'irrelevant', params[:train])
  end
end

app/controllers/staticpages_controller.rb
class StaticpagesController < ApplicationController
  def about
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  def show
    @topic = params[:topic].gsub(" ", "%20")

    #still unable to determine why the services do not respond correctly when not instantiated in the TopicsController class. 
    #Future fix - move topicStoriesHelper into a StoriesService
    return topicStoriesHelper
  end

  def topicStoriesHelper
    nyt_array = NytService.new(@topic).stories_array
    npr_array = NprService.new(@topic).stories_array
    amazon_array = AmazonService.new(@topic).attributes_array
    coursera_array = CourseraService.new(@topic).courses_array
    goodreads_array = GoodReadsService.new(@topic).books_array

    stories_array = (npr_array + amazon_array + coursera_array + nyt_array + goodreads_array)

    @stories_array = stories_array.sort do |x,y|
      Score.classifications(@topic,y['title'])['relevant'] <=> Score.classifications(@topic,x['title'])['relevant']
    end
  end
  
end

app/views/articles/show.html.erb
<div class="tree">
  <div class="row" id="about-div">
  	<div class="col-md-2"></div>
  	<div class="col-md-8">
  		<div id="chart">
  		</div>
  	</div>
  	<div class="col-md-2"></div>
  </div>

  <div class="loader4">
    <div>
      <div>
        <div>
          <div>
            <div>
              <div>
                <div>
                  <div>
                    <div>
                      <div></div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>KnowledgeBase</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
</head>
<body class="page-body">

		<nav class="navbar navbar-default" role="navigation">
		  <div class="container-fluid">
		    <div class="navbar-header">
		      <%= link_to image_tag("logo.png", height: '40', width: '225', id:"logo-img"), root_path %>
		    </div>

        <form class="navbar-form navbar-right" role="search">
          <%if current_page?(:controller => 'articles', action: "show")  %>
            <input type="text" id="current-topic" placeholder="Choose a topic below or type one in" class="form-control">
          <%else %>
            <input type="text" id="current-topic" placeholder="Choose a topic" class="form-control">
          <% end %>
          <button id="topic-submit" class="btn btn-default" href='/topic?topic='>Learn More About This Topic</button>
        </form>
		  </div>
		</nav>

  <div class="container main-content">
    <div class="row" id="error-message">
    </div>
    <div id="yielded-content">
      <%= yield %>
    </div>
  </div> 

  <div class="footer-text">
      <div class="footer-text-left">
        <div class="menu">
          <ul>
            <li>
              <%= link_to "About KnowledgeBase", staticpages_about_path %>
            </li>
          </ul>
        </div>
      </div>
      <div class="footer-text-right">
        <div class="copyright">Made with ♥ @ The Flatiron School by <%= link_to "Karim Butt", "https://twitter.com/karimbutt", target:"_blank" %> & <%= link_to "Elizabeth Wolensky", "https://twitter.com/sailor_flares", target:"_blank" %></a></div>
      </div>
      <div class="clear"></div>
    </div>   
  

</body>
</html>

app/views/staticpages/about.html.erb
<div class="tree">
  <div class="row" id="chart-div">
  	<div class="col-md-2"></div>
    <div class="col-md-8">
      <div id="for_height">
        
      	<h1>KnowledgeBase is a tool for information junkies...</h1> <br>
      	
      	<h3 class="one">When you select a topic either through our predefined tree or through the search bar...</h3>
      	<center><%= image_tag "select_topic.png", width:"50%", height:"50%", class:"one" %></center> <br>
      	
      	<h3 class="two">We look across a number of various content sources, utilizing their APIs, for that topic...</h3>
      	<center><%= image_tag "api_logos.png", width:"50%", height:"50%", class:"two" %></center> <br>
      	
      	<h3 class="three">And integrated a naive Bayes classifier to provide you with the highest quality, most relevant content based on your and other user's rating of content relevance...</h3>
      	<center><%= image_tag "machine_learning.png", width:"50%", height:"50%", class:"three" %></center> <br>
      </div>
    </div>
    <div class="col-md-2"></div>
  </div>
</div>

<div class="loader4">
  <div>
    <div>
      <div>
        <div>
          <div>
            <div>
              <div>
                <div>
                  <div>
                    <div></div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/topics/_story.html.erb
<div class="panel panel-info">
  <div class="panel-heading">
    <h3 class="panel-title">
      <a href="<%=story["link"]%>">  
        <%=story["title"]%>    
      </a>
    </h3>
  </div>
  <div class="panel-body panel-extras">
    <div class="image">
      <img class="center-block image-fit" src="<%=story["img_src"]%>" alt="<%=story["title"]%>">
      <button type="button"
              class="btn btn-default btn-up"
              train="<%=story['title']%>"
              topic="<%=@topic%>">
        <span class="glyphicon glyphicon-ok"></span><span class="btn-text">Apt</span>
      </button>
      <button type="button"
              class="btn btn-default btn-down"
              train="<%=story['title']%>"
              topic="<%=@topic%>">
        <span class="glyphicon glyphicon-remove"></span><span class="btn-text">Off-topic</span>
      </button>
    </div>
  </div>
</div>

app/views/topics/show.html.erb
<h1 class="topic-title"><%=@topic.gsub("%20", " ").titleize %></h1>
<div class="stories">
  <% @stories_array.each do |story| %>
    <%= render partial: 'topics/story', :locals => {:story => story} %>  
  <% end %>
</div>


<div class="loader4">
  <div>
    <div>
      <div>
        <div>
          <div>
            <div>
              <div>
                <div>
                  <div>
                    <div></div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
 $( document ).ready(function() {
   $(".btn-up").click(function(e) {
       var train = $(this).attr("train");
       var topic = $(this).attr("topic");
       $.ajax({
         type: 'POST', 
         url:'/relevant', 
         data:{
          train: train,
          topic: topic
         }
       });
       console.log("upvote");
       $(this).css('background-color', '#80B94A');
       $(this).siblings()[1].remove();
     });

   $(".btn-down").click(function(e) {
       var train = $(this).attr("train");
       var topic = $(this).attr("topic");
       $.ajax({
         type: 'POST', 
         url:'/irrelevant', 
         data:{
          train: train,
          topic: topic
         }
       });
       console.log("downvote");
       $(this).closest(".panel").remove();
     });
   });
</script>

app/views/users/show.html.erb
<%= debug AmazonScraper.new("exercise").attributes_array.first.children.%>